name: Publish on PR merge

on:
    pull_request:
        types: closed

jobs:
    build-and-publish:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
              with:
                  ref: master

            - name: Configure Git
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --local user.name "GitHub Publish Action"
                  git config --local user.email "action@users.noreply.github.com"
                  git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  git checkout master

            - name: Setup node
              uses: actions/setup-node@v1.1.0
              with:
                  node-version: "10.x"
                  registry-url: "https://registry.npmjs.org"

            - run: yarn install

            - name: Publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn release --yes
